// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: hRsY5NbPeCQT1m4ubZULqa
// Component: i70_KLpb3HC
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Header from "../../Header"; // plasmic-import: ehCSLGzmt76/component
import SocialFooter from "../../SocialFooter"; // plasmic-import: Zmr6lqTMMC/component

import { useScreenVariants as useScreenVariantsc8HlPs3Ggff } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: C8HlPs3Ggff/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import * as projectcss from "./plasmic_aditi_rajagopal_personal_website_2022.module.css"; // plasmic-import: hRsY5NbPeCQT1m4ubZULqa/projectcss
import * as sty from "./PlasmicPto.module.css"; // plasmic-import: i70_KLpb3HC/css

export type PlasmicPto__VariantMembers = {};

export type PlasmicPto__VariantsArgs = {};
type VariantPropType = keyof PlasmicPto__VariantsArgs;
export const PlasmicPto__VariantProps = new Array<VariantPropType>();

export type PlasmicPto__ArgsType = {};
type ArgPropType = keyof PlasmicPto__ArgsType;
export const PlasmicPto__ArgProps = new Array<ArgPropType>();

export type PlasmicPto__OverridesType = {
  root?: p.Flex<"div">;
  header?: p.Flex<typeof Header>;
  freeBox?: p.Flex<"div">;
  socialFooter?: p.Flex<typeof SocialFooter>;
};

export interface DefaultPtoProps {
  dataFetches: PlasmicPto__Fetches;
}

function PlasmicPto__RenderFunc(props: {
  variants: PlasmicPto__VariantsArgs;
  args: PlasmicPto__ArgsType;
  overrides: PlasmicPto__OverridesType;
  dataFetches?: PlasmicPto__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsc8HlPs3Ggff()
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{"Working with Me"}</title>
        <meta key="og:title" property="og:title" content={"Working with Me"} />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <Header
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames("__wab_instance", sty.header)}
          />

          <div
            data-plasmic-name={"freeBox"}
            data-plasmic-override={overrides.freeBox}
            className={classNames(projectcss.all, sty.freeBox)}
          />

          <SocialFooter
            data-plasmic-name={"socialFooter"}
            data-plasmic-override={overrides.socialFooter}
            className={classNames("__wab_instance", sty.socialFooter)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "header", "freeBox", "socialFooter"],
  header: ["header"],
  freeBox: ["freeBox"],
  socialFooter: ["socialFooter"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  header: typeof Header;
  freeBox: "div";
  socialFooter: typeof SocialFooter;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicPto__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicPto__VariantsArgs;
    args?: PlasmicPto__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicPto__Fetches;
  } & Omit<PlasmicPto__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicPto__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicPto__ArgProps,
      internalVariantPropNames: PlasmicPto__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicPto__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPto";
  } else {
    func.displayName = `PlasmicPto.${nodeName}`;
  }
  return func;
}

export const PlasmicPto = Object.assign(
  // Top-level PlasmicPto renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    freeBox: makeNodeComponent("freeBox"),
    socialFooter: makeNodeComponent("socialFooter"),

    // Metadata about props expected for PlasmicPto
    internalVariantProps: PlasmicPto__VariantProps,
    internalArgProps: PlasmicPto__ArgProps
  }
);

export default PlasmicPto;
/* prettier-ignore-end */
